import { Component } from '@stencil/core';


@Component({
  tag: 'wc-app',
  styleUrl: 'wc-app.scss'
})
export class WcApp {

  render() {
    return (
      <ion-app>
        <div id="main-div">
          <div class="app">
            <stencil-router>
              <stencil-route url='/' component='wc-home' exact={true}>
              </stencil-route>
              <stencil-route
                url="/components/:pageName"
                routeRender={(props: { [key: string]: any }) => {
                  const map = {
                    'ionic-core': '/assets/docs/ionic-core/ionic-core.html',
                    'ion-action-sheet': '/assets/docs/ionic-core/ion-action-sheet.html',
                    'ion-action-sheet-controller': '/assets/docs/ionic-core/ion-action-sheet-controller.html',
                    'ion-alert-controller': '/assets/docs/ionic-core/ion-alert-controller.html',
                    'ion-alert': '/assets/docs/ionic-core/ion-alert.html',
                    'ion-animation-controller': '/assets/docs/ionic-core/ion-animation-controller.html',
                    'ion-app': '/assets/docs/ionic-core/ion-app.html',
                    'ion-avatar': '/assets/docs/ionic-core/ion-avatar.html',
                    'ion-back-button': '/assets/docs/ionic-core/ion-back-button.html',
                    'ion-backdrop': '/assets/docs/ionic-core/ion-backdrop.html',
                    'ion-badge': '/assets/docs/ionic-core/ion-badge.html',
                    'ion-button': '/assets/docs/ionic-core/ion-button.html',
                    'ion-buttons': '/assets/docs/ionic-core/ion-buttons.html',
                    'ion-card-content': '/assets/docs/ionic-core/ion-card-content.html',
                    'ion-card-header': '/assets/docs/ionic-core/ion-card-header.html',
                    'ion-card-subtitle': '/assets/docs/ionic-core/ion-card-subtitle.html',
                    'ion-card-title': '/assets/docs/ionic-core/ion-card-title.html',
                    'ion-card': '/assets/docs/ionic-core/ion-card.html',
                    'ion-checkbox': '/assets/docs/ionic-core/ion-checkbox.html',
                    'ion-chip-button': '/assets/docs/ionic-core/ion-chip-button.html',
                    'ion-chip': '/assets/docs/ionic-core/ion-chip.html',
                    'ion-col': '/assets/docs/ionic-core/ion-col.html',
                    'ion-content': '/assets/docs/ionic-core/ion-content.html',
                    'ion-datetime': '/assets/docs/ionic-core/ion-datetime.html',
                    'ion-fab-button': '/assets/docs/ionic-core/ion-fab-button.html',
                    'ion-fab-list': '/assets/docs/ionic-core/ion-fab-list.html',
                    'ion-fab': '/assets/docs/ionic-core/ion-fab.html',
                    'ion-footer': '/assets/docs/ionic-core/ion-footer.html',
                    'ion-gesture-controller': '/assets/docs/ionic-core/ion-gesture-controller.html',
                    'ion-gesture': '/assets/docs/ionic-core/ion-gesture.html',
                    'ion-grid': '/assets/docs/ionic-core/ion-grid.html',
                    'ion-header': '/assets/docs/ionic-core/ion-header.html',
                    'ion-icon': '/assets/docs/ionic-core/ion-icon.html',
                    'ion-infinite-scroll-content': '/assets/docs/ionic-core/ion-infinite-scroll-content.html',
                    'ion-infinite-scroll': '/assets/docs/ionic-core/ion-infinite-scroll.html',
                    'ion-input': '/assets/docs/ionic-core/ion-input.html',
                    'ion-item-divider': '/assets/docs/ionic-core/ion-item-divider.html',
                    'ion-item-option': '/assets/docs/ionic-core/ion-item-option.html',
                    'ion-item-options': '/assets/docs/ionic-core/ion-item-options.html',
                    'ion-item-sliding': '/assets/docs/ionic-core/ion-item-sliding.html',
                    'ion-item': '/assets/docs/ionic-core/ion-item.html',
                    'ion-keyboard-controller': '/assets/docs/ionic-core/ion-keyboard-controller.html',
                    'ion-label': '/assets/docs/ionic-core/ion-label.html',
                    'ion-list-header': '/assets/docs/ionic-core/ion-list-header.html',
                    'ion-list': '/assets/docs/ionic-core/ion-list.html',
                    'ion-loading-controller': '/assets/docs/ionic-core/ion-loading-controller.html',
                    'ion-loading': '/assets/docs/ionic-core/ion-loading.html',
                    'ion-menu-controller': '/assets/docs/ionic-core/ion-menu-controller.html',
                    'ion-menu': '/assets/docs/ionic-core/ion-menu.html',
                    'ion-modal-controller': '/assets/docs/ionic-core/ion-modal-controller.html',
                    'ion-modal': '/assets/docs/ionic-core/ion-modal.html',
                    'ion-nav': '/assets/docs/ionic-core/ion-nav.html',
                    'ion-navbar': '/assets/docs/ionic-core/ion-navbar.html',
                    'ion-note': '/assets/docs/ionic-core/ion-note.html',
                    'ion-page': '/assets/docs/ionic-core/ion-page.html',
                    'ion-picker-column': '/assets/docs/ionic-core/ion-picker-column.html',
                    'ion-picker-controller': '/assets/docs/ionic-core/ion-picker-controller.html',
                    'ion-picker': '/assets/docs/ionic-core/ion-picker.html',
                    'ion-popover-controller': '/assets/docs/ionic-core/ion-popover-controller.html',
                    'ion-popover': '/assets/docs/ionic-core/ion-popover.html',
                    'ion-radio-group': '/assets/docs/ionic-core/ion-radio-group.html',
                    'ion-radio': '/assets/docs/ionic-core/ion-radio.html',
                    'ion-range-knob': '/assets/docs/ionic-core/ion-range-knob.html',
                    'ion-range': '/assets/docs/ionic-core/ion-range.html',
                    'ion-reorder-group': '/assets/docs/ionic-core/ion-reorder-group.html',
                    'ion-reorder': '/assets/docs/ionic-core/ion-reorder.html',
                    'ion-route-link': '/assets/docs/ionic-core/ion-route-link.html',
                    'ion-route': '/assets/docs/ionic-core/ion-route.html',
                    'ion-router-controller': '/assets/docs/ionic-core/ion-router-controller.html',
                    'ion-row': '/assets/docs/ionic-core/ion-row.html',
                    'ion-scroll': '/assets/docs/ionic-core/ion-scroll.html',
                    'ion-searchbar': '/assets/docs/ionic-core/ion-searchbar.html',
                    'ion-segment-button': '/assets/docs/ionic-core/ion-segment-button.html',
                    'ion-segment': '/assets/docs/ionic-core/ion-segment.html',
                    'ion-select-option': '/assets/docs/ionic-core/ion-select-option.html',
                    'ion-select-popover': '/assets/docs/ionic-core/ion-select-popover.html',
                    'ion-select': '/assets/docs/ionic-core/ion-select.html',
                    'ion-skeleton-text': '/assets/docs/ionic-core/ion-skeleton-text.html',
                    'ion-slide': '/assets/docs/ionic-core/ion-slide.html',
                    'ion-slides': '/assets/docs/ionic-core/ion-slides.html',
                    'ion-spinner': '/assets/docs/ionic-core/ion-spinner.html',
                    'ion-split-pane': '/assets/docs/ionic-core/ion-split-pane.html',
                    'ion-tab-button': '/assets/docs/ionic-core/ion-tab-button.html',
                    'ion-tab': '/assets/docs/ionic-core/ion-tab.html',
                    'ion-tabbar': '/assets/docs/ionic-core/ion-tabbar.html',
                    'ion-tabs': '/assets/docs/ionic-core/ion-tabs.html',
                    'ion-textarea': '/assets/docs/ionic-core/ion-textarea.html',
                    'ion-thumbnail': '/assets/docs/ionic-core/ion-thumbnail.html',
                    'ion-title': '/assets/docs/ionic-core/ion-title.html',
                    'ion-toast-controller': '/assets/docs/ionic-core/ion-toast-controller.html',
                    'ion-toast': '/assets/docs/ionic-core/ion-toast.html',
                    'ion-toggle': '/assets/docs/ionic-core/ion-toggle.html',
                    'ion-toolbar': '/assets/docs/ionic-core/ion-toolbar.html',
                    'ion-util': '/assets/examples/ionic-core/ion-util.html',
                  };
                  const exampleMap = {
                    'ionic-core': '/assets/examples/ionic-core/ionic-core.html',
                    'ion-action-sheet': 'https://stackblitz.com/edit/ajonp-ion-action-sheet-controller?embed=1&file=index.html&view=preview',
                    'ion-action-sheet-controller': 'https://stackblitz.com/edit/ajonp-ion-action-sheet-controller?embed=1&file=index.html&view=preview',
                    'ion-alert-controller': 'https://stackblitz.com/edit/ajonp-ion-alert-controller?embed=1&file=index.html&view=preview',
                    'ion-alert': 'https://stackblitz.com/edit/ajonp-ion-alert?embed=1&file=index.html&view=preview',
                    'ion-animation-controller': 'https://stackblitz.com/edit/ajonp-ion-animation-controller?embed=1&file=index.html&view=preview',
                    'ion-app': '/assets/examples/ionic-core/ion-app.html',
                    'ion-avatar': 'https://stackblitz.com/edit/ajonp-ion-avatar?embed=1&file=index.html&view=preview',
                    'ion-back-button': 'https://stackblitz.com/edit/ajonp-ion-back-button?embed=1&file=index.html&view=preview',
                    'ion-backdrop': 'https://stackblitz.com/edit/ajonp-ion-backdrop?embed=1&file=index.html&view=preview',
                    'ion-badge': 'https://stackblitz.com/edit/ajonp-ion-badge?embed=1&file=index.html&view=preview',
                    'ion-button': 'https://stackblitz.com/edit/ajonp-ion-button?embed=1&file=index.ts&view=preview',
                    'ion-buttons': 'https://stackblitz.com/edit/ajonp-ion-buttons?embed=1&file=index.html&view=preview',
                    'ion-card-content': 'https://stackblitz.com/edit/ajonp-ion-card-content?embed=1&file=index.html&view=preview',
                    'ion-card-header': 'https://stackblitz.com/edit/ajonp-ion-card-header?embed=1&file=index.html&view=preview',
                    'ion-card-subtitle': 'https://stackblitz.com/edit/ajonp-ion-card-subtitle?embed=1&file=index.html&view=preview',
                    'ion-card-title': 'https://stackblitz.com/edit/ajonp-ion-card-title?embed=1&file=index.html&view=preview  ',
                    'ion-card': 'https://stackblitz.com/edit/ajonp-ion-card?embed=1&file=index.html&view=preview',
                    'ion-checkbox': 'https://stackblitz.com/edit/ajonp-ion-checkbox?embed=1&file=index.html&view=preview',
                    'ion-chip-button': 'https://stackblitz.com/edit/ajonp-ion-chip-button?embed=1&file=index.html&view=preview',
                    'ion-chip': 'https://stackblitz.com/edit/ajonp-ion-chip?embed=1&file=index.html&view=preview',
                    'ion-col': '/assets/examples/ionic-core/ion-col.html',
                    'ion-content': '/assets/examples/ionic-core/ion-content.html',
                    'ion-datetime': '/assets/examples/ionic-core/ion-datetime.html',
                    'ion-fab-button': '/assets/examples/ionic-core/ion-fab-button.html',
                    'ion-fab-list': '/assets/examples/ionic-core/ion-fab-list.html',
                    'ion-fab': '/assets/examples/ionic-core/ion-fab.html',
                    'ion-footer': '/assets/examples/ionic-core/ion-footer.html',
                    'ion-gesture-controller': '/assets/examples/ionic-core/ion-gesture-controller.html',
                    'ion-gesture': '/assets/examples/ionic-core/ion-gesture.html',
                    'ion-grid': '/assets/examples/ionic-core/ion-grid.html',
                    'ion-header': '/assets/examples/ionic-core/ion-header.html',
                    'ion-icon': '/assets/examples/ionic-core/ion-icon.html',
                    'ion-infinite-scroll-content': '/assets/examples/ionic-core/ion-infinite-scroll-content.html',
                    'ion-infinite-scroll': '/assets/examples/ionic-core/ion-infinite-scroll.html',
                    'ion-input': '/assets/examples/ionic-core/ion-input.html',
                    'ion-item-divider': '/assets/examples/ionic-core/ion-item-divider.html',
                    'ion-item-option': '/assets/examples/ionic-core/ion-item-option.html',
                    'ion-item-options': '/assets/examples/ionic-core/ion-item-options.html',
                    'ion-item-sliding': '/assets/examples/ionic-core/ion-item-sliding.html',
                    'ion-item': '/assets/examples/ionic-core/ion-item.html',
                    'ion-keyboard-controller': '/assets/examples/ionic-core/ion-keyboard-controller.html',
                    'ion-label': '/assets/examples/ionic-core/ion-label.html',
                    'ion-list-header': '/assets/examples/ionic-core/ion-list-header.html',
                    'ion-list': '/assets/examples/ionic-core/ion-list.html',
                    'ion-loading-controller': '/assets/examples/ionic-core/ion-loading-controller.html',
                    'ion-loading': '/assets/examples/ionic-core/ion-loading.html',
                    'ion-menu-controller': '/assets/examples/ionic-core/ion-menu-controller.html',
                    'ion-menu': '/assets/examples/ionic-core/ion-menu.html',
                    'ion-modal-controller': '/assets/examples/ionic-core/ion-modal-controller.html',
                    'ion-modal': '/assets/examples/ionic-core/ion-modal.html',
                    'ion-nav': '/assets/examples/ionic-core/ion-nav.html',
                    'ion-navbar': '/assets/examples/ionic-core/ion-navbar.html',
                    'ion-note': '/assets/examples/ionic-core/ion-note.html',
                    'ion-page': '/assets/examples/ionic-core/ion-page.html',
                    'ion-picker-column': '/assets/examples/ionic-core/ion-picker-column.html',
                    'ion-picker-controller': '/assets/examples/ionic-core/ion-picker-controller.html',
                    'ion-picker': '/assets/examples/ionic-core/ion-picker.html',
                    'ion-popover-controller': '/assets/examples/ionic-core/ion-popover-controller.html',
                    'ion-popover': '/assets/examples/ionic-core/ion-popover.html',
                    'ion-radio-group': '/assets/examples/ionic-core/ion-radio-group.html',
                    'ion-radio': '/assets/examples/ionic-core/ion-radio.html',
                    'ion-range-knob': '/assets/examples/ionic-core/ion-range-knob.html',
                    'ion-range': '/assets/examples/ionic-core/ion-range.html',
                    'ion-reorder-group': '/assets/examples/ionic-core/ion-reorder-group.html',
                    'ion-reorder': '/assets/examples/ionic-core/ion-reorder.html',
                    'ion-route-link': '/assets/examples/ionic-core/ion-route-link.html',
                    'ion-route': '/assets/examples/ionic-core/ion-route.html',
                    'ion-router-controller': '/assets/examples/ionic-core/ion-router-controller.html',
                    'ion-row': '/assets/examples/ionic-core/ion-row.html',
                    'ion-scroll': '/assets/examples/ionic-core/ion-scroll.html',
                    'ion-searchbar': '/assets/examples/ionic-core/ion-searchbar.html',
                    'ion-segment-button': '/assets/examples/ionic-core/ion-segment-button.html',
                    'ion-segment': '/assets/examples/ionic-core/ion-segment.html',
                    'ion-select-option': '/assets/examples/ionic-core/ion-select-option.html',
                    'ion-select-popover': '/assets/examples/ionic-core/ion-select-popover.html',
                    'ion-select': '/assets/examples/ionic-core/ion-select.html',
                    'ion-skeleton-text': '/assets/examples/ionic-core/ion-skeleton-text.html',
                    'ion-slide': '/assets/examples/ionic-core/ion-slide.html',
                    'ion-slides': '/assets/examples/ionic-core/ion-slides.html',
                    'ion-spinner': '/assets/examples/ionic-core/ion-spinner.html',
                    'ion-split-pane': '/assets/examples/ionic-core/ion-split-pane.html',
                    'ion-tab-button': '/assets/examples/ionic-core/ion-tab-button.html',
                    'ion-tab': '/assets/examples/ionic-core/ion-tab.html',
                    'ion-tabbar': '/assets/examples/ionic-core/ion-tabbar.html',
                    'ion-tabs': '/assets/examples/ionic-core/ion-tabs.html',
                    'ion-textarea': '/assets/examples/ionic-core/ion-textarea.html',
                    'ion-thumbnail': '/assets/examples/ionic-core/ion-thumbnail.html',
                    'ion-title': '/assets/examples/ionic-core/ion-title.html',
                    'ion-toast-controller': '/assets/examples/ionic-core/ion-toast-controller.html',
                    'ion-toast': '/assets/examples/ionic-core/ion-toast.html',
                    'ion-toggle': '/assets/examples/ionic-core/ion-toggle.html',
                    'ion-toolbar': '/assets/examples/ionic-core/ion-toolbar.html',
                    'ion-util': '/assets/examples/ionic-core/ion-util.html',
                  };
                  return (
                    <wc-components
                      pages={[map[props.match.params.pageName]]}
                      examples={[exampleMap[props.match.params.pageName]]}
                    />
                  );
                }}
              />
            </stencil-router>
          </div>
        </div>
      </ion-app>
    );
  }
}
