/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';


import {
  SiteMenu as WcSiteMenu
} from './components/wc-site-menu/wc-site-menu';

declare global {
  interface HTMLWcSiteMenuElement extends WcSiteMenu, HTMLElement {
  }
  var HTMLWcSiteMenuElement: {
    prototype: HTMLWcSiteMenuElement;
    new (): HTMLWcSiteMenuElement;
  };
  interface HTMLElementTagNameMap {
    "wc-site-menu": HTMLWcSiteMenuElement;
  }
  interface ElementTagNameMap {
    "wc-site-menu": HTMLWcSiteMenuElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "wc-site-menu": JSXElements.WcSiteMenuAttributes;
    }
  }
  namespace JSXElements {
    export interface WcSiteMenuAttributes extends HTMLAttributes {
      
    }
  }
}

